### ISSUE TITLE
query

### ISSUE THREAD

**Issue by Arwa200** [guilherme-toti/instagram-auto-liker#1]
hi, I've tried to running this code but I got this in terminal
could you please help me to fix to make this code run correctly
![Screen Shot 2019-06-09 at 7 22 00 AM](https://user-images.githubusercontent.com/42224049/59154995-599a1900-8a87-11e9-8b8b-10fce19eb6c8.png)

also is there any way to make an auto like for following

**Comment by josemilagre** [comment]
I have the same problem!

Traceback (most recent call last):
  File "C:\Users\Jose Milagre\instagram-auto-liker-master\run.py", line 19, in <module>
    driver = webdriver.Chrome('chromedriver_windows.exe')
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
